version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/build"
      - ".github/actions/setup"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
