name: setup

inputs:
  build:
    type: boolean
    default: false
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: restore cache
      uses: actions/cache@v4
      id: toolchain-cache
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: install rust toolchain
      if: steps.toolchain-cache.outputs.cache-hit != 'true'
      uses: dtolnay/rust-toolchain@stable
      with:
        components: cargo,clippy,rustfmt

    - name: cargo build
      if: inputs.build == true || inputs.build == 'true'
      shell: bash
      run: cargo build
