name: setup
description: Install the rust toolchain

outputs:
  rust-cache-key:
    description: cache key returned by dtolnay/rust-toolchain
    value: ${{ steps.toolchain-meta.outputs.rust-cache-key }}
  rust-name:
    description: toolchain name returned by dtolnay/rust-toolchain
    value: ${{ steps.toolchain-meta.outputs.rust-name }}

runs:
  using: composite
  steps:
    - name: setup environment vars
      id: setup-env
      shell: bash
      env:
        TOOLCHAIN_HASH: ${{ hashFiles('.github/actions/setup/**') }}
      run: |
        : ${RUNNER_OS:?} ${RUNNER_ARCH:?}
        : ${TOOLCHAIN_HASH:?}

        set-out() { echo "${1}=${2}" >> $GITHUB_OUTPUT; }
        set-env() { echo "${1}=${2}" >> $GITHUB_ENV; }

        TOOLCHAIN_PREFIX="toolchain-${RUNNER_OS}-${RUNNER_ARCH}::"
        set-out toolchain-cache-prefix "${TOOLCHAIN_PREFIX}"
        set-out toolchain-cache-key    "${TOOLCHAIN_PREFIX}${TOOLCHAIN_HASH}"

    - name: restore toolchain cache
      id: cache-restore
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.cargo
        key: ${{ steps.setup-env.outputs.toolchain-cache-key }}
        restore-keys: ${{ steps.setup-env.outputs.toolchain-cache-prefix }}

    - name: install rust toolchain
      id: toolchain-install
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      with:
        components: cargo,clippy,rustfmt

    - name: save toolchain meta
      id: toolchain-meta-save
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      env:
        _CACHE_KEY: ${{ steps.toolchain-install.outputs.cachekey }}
        _CACHE_NAME: ${{ steps.toolchain-install.outputs.name }}
      run: |
        {
          echo "rust-cache-key=${_CACHE_KEY:?}"
          echo "rust-name=${_CACHE_NAME:?}"
        } > ~/.cargo/.ci-meta

    - name: restore toolchain meta
      id: toolchain-meta
      shell: bash
      run: |
        test -e ~/.cargo/.ci-meta || {
          echo "ERROR: ~/.cargo/.ci-meta not found"
          exit 1
        }
        cat ~/.cargo/.ci-meta | tee -a $GITHUB_OUTPUT

    - name: save toolchain cache
      id: cache-save
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.cargo
        key: ${{ steps.setup-env.outputs.toolchain-cache-key }}
