[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "aarch64-unknown-linux-musl", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false

[dist.github-custom-runners]
# defaults
global = "ubuntu-24.04"
x86_64-unknown-linux-gnu = "ubuntu-24.04"

# dependabot BEGIN
[dist.github-action-commits]
"actions/checkout" = "08c6903cd8c0fde910a37f88322edcfb5dd907a8"
"actions/download-artifact" = "634f93cb2916e3fdff6788551b99b062d0335ce0"
"actions/upload-artifact" = "330a01c490aca151604b8cf639adc76d48f6c5d4"
# dependabot END
