mod testlib;
use testlib::*;

#[integration]
mod nginx_conf {
    use super::*;

    #[test]
    fn header_comments() {
        let mut cmd = testlib::RUSTY.cmd();
        cmd.env("RESTY_CLI_COMPAT_VERSION", "v0.29");

        let nginx = testlib::testbin("print_nginx_conf");
        cmd.args(["--nginx", nginx.as_str(), "-e", "nothing"]);

        assert_all_matched!(
            vec![
                format!("# generated by rusty-cli v{}", env!("CARGO_PKG_VERSION")),
                "# resty-cli compat v0.29".into(),
            ],
            cmd.stdout_lines()
        );

        assert_empty!(cmd.stderr_lines());
    }

    #[test]
    fn sections() {
        let mut cmd = testlib::RUSTY.cmd();

        let nginx = testlib::testbin("print_nginx_conf");
        cmd.args(["--nginx", nginx.as_str(), "-e", "nothing"]);

        assert_all_matched!(
            vec![
                "events {",
                "stream {",
                "http {",
                "init_by_lua_block {",
                "init_worker_by_lua_block {",
            ],
            cmd.stdout_lines()
        );

        assert_empty!(cmd.stderr_lines());
    }
}
