mod testlib;
use testlib::*;

#[integration]
mod nginx_conf {
    use super::*;

    #[test]
    fn header_comments() {
        let mut cmd = testlib::RUSTY.cmd();
        cmd.env("RESTY_CLI_COMPAT_VERSION", "v0.29");

        let nginx = testlib::testbin("print_nginx_conf");
        cmd.args(["--nginx", nginx.as_str(), "-e", "nothing"]);

        assert_all_matched!(
            vec![
                format!("# generated by rusty-cli v{}", env!("CARGO_PKG_VERSION")),
                "# resty-cli compat v0.29".into(),
            ],
            cmd.stdout_lines()
        );

        assert_empty!(cmd.stderr_lines());
    }

    #[bin_test]
    fn sections(bin: testlib::Bin) {
        let mut cmd = bin.cmd();

        let nginx = testlib::testbin("print_nginx_conf");
        cmd.args(["--nginx", nginx.as_str(), "-e", "nothing"]);

        assert_all_matched!(
            vec![
                "events {",
                "stream {",
                "http {",
                "init_by_lua_block {",
                "init_worker_by_lua_block {",
            ],
            cmd.stdout_lines()
        );

        assert_empty!(cmd.stderr_lines());
    }

    #[bin_test]
    fn load_module(bin: testlib::Bin) {
        min_resty_version!(0, 31);

        let mut cmd = bin.cmd();

        let nginx = testlib::testbin("print_nginx_conf");
        cmd.args([
            "--nginx",
            nginx.as_str(),
            "--load-module",
            "/path/to/module_a.so",
            "--load-module",
            "/path/to/module_b.so",
            "-e",
            "nothing",
        ]);

        let stdout = cmd.stdout_lines();

        assert_all_matched!(
            vec![
                "load_module /path/to/module_a.so;",
                "load_module /path/to/module_b.so;",
            ],
            stdout.clone()
        );

        let load_module_pos = stdout
            .iter()
            .position(|line| line.contains("load_module"))
            .expect("load_module directive not found");
        let daemon_pos = stdout
            .iter()
            .position(|line| line.contains("daemon off"))
            .expect("daemon off directive not found");

        assert!(
            load_module_pos < daemon_pos,
            "load_module should appear before daemon off"
        );

        assert_empty!(cmd.stderr_lines());
    }

    #[bin_test]
    fn dump_nginx_conf(bin: testlib::Bin) {
        let mut cmd = bin.cmd();

        // validates that rusty/resty don't actually attempt to run nginx
        // in this code path
        cmd.args([
            "--nginx",
            "/i/definitely/do/not/exist",
        ]);

        cmd.args([
            "--dump-nginx-conf",
            "-e",
            "print('hello')",
        ]);

        let stdout = cmd.stdout_lines();

        assert_all_matched!(
            vec![
                "events {",
                "stream {",
                "http {",
                "init_by_lua_block {",
                "init_worker_by_lua_block {",
            ],
            stdout
        );

        assert_empty!(cmd.stderr_lines());
    }
}
