name: lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

# https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
jobs:
  init:
    uses: ./.github/workflows/toolchain-init.yml
    secrets: inherit

  check:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/cargo@v1
        with:
          command: check

  rustfmt:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup component add clippy

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps -- -D warnings
