name: lint

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint.yml'
      - 'Cargo.*'
      - '**.rs'

  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/lint.yml'
      - 'Cargo.*'
      - '**.rs'

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: cargo check
        run: cargo check

      - name: cargo check (NGINX_PATH)
        run: cargo check
        env:
          NGINX_PATH: /my/nginx

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: install rustfmt
        run: rustup component add rustfmt

      - name: cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: install clippy
        run: rustup component add clippy

      - name: cargo clippy
        run: cargo clippy --no-deps -- -D warnings
