name: lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

# https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml

      - uses: actions-rs/cargo@v1
        with:
          command: check

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml

      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml

      - run: rustup component add clippy

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps -- -D warnings
