name: lint

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint.yml'
      - 'Cargo.*'
      - '**.rs'

  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/lint.yml'
      - 'Cargo.*'
      - '**.rs'

defaults:
  run:
    shell: bash

# https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - uses: actions-rs/cargo@v1
        with:
          command: check

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: rustup component add clippy

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps -- -D warnings
