name: compatibility tests

on:
  workflow_call: {}

defaults:
  run:
    shell: bash

jobs:
  compat:
    name: resty-cli compat ${{ matrix.resty-cli }} / ${{ matrix.openresty }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - openresty: 1.19.9.1
            resty-cli: v0.28
            openssl: 1.1.1n
            openresty-opts: >
              --with-compat
              --with-pcre-jit
              --with-stream
              --with-threads
              --with-http_ssl_module
              --with-stream_ssl_module
              --with-stream_ssl_preread_module

          - openresty: 1.21.4.3
            resty-cli: v0.29
            openssl: 1.1.1n
            openresty-opts: >
              --with-compat
              --with-pcre-jit
              --with-stream
              --with-threads
              --with-http_ssl_module
              --with-stream_ssl_module
              --with-stream_ssl_preread_module

          - openresty: 1.25.3.2
            resty-cli: v0.30
            openssl: 1.1.1w
            openresty-opts: >
              --with-compat
              --with-pcre-jit
              --with-stream
              --with-threads
              --with-http_ssl_module
              --with-stream_ssl_module
              --with-stream_ssl_preread_module

          - openresty: 1.27.1.1
            resty-cli: v0.30
            openssl: 3.0.15
            openresty-opts: >
              --with-compat
              --with-pcre-jit
              --with-stream
              --with-threads
              --with-http_ssl_module
              --with-stream_ssl_module
              --with-stream_ssl_preread_module

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

      - name: install deps
        id: deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gdb libpcre3
          gdb --version

      - name: set resty-cli compat env var
        run: echo "RESTY_CLI_COMPAT_VERSION=${{ matrix.resty-cli }}" >> $GITHUB_ENV

      - name: set OpenResty prefix
        run: |
          echo OPENRESTY_PREFIX=${GITHUB_WORKSPACE}/openresty/${{ matrix.openresty }} >> $GITHUB_ENV
          echo PERL5LIB=${GITHUB_WORKSPACE}/work/lib/cpanm/lib/perl5 >> $GITHUB_ENV

      - name: Store OpenResty build opts
        run: |
          > .resty-opts
          echo '${{ matrix.openresty-opts }}' >> .resty-opts
          echo '${{ matrix.resty-cli }}'      >> .resty-opts
          echo '${{ matrix.openssl }}'        >> .resty-opts

      - name: cache OpenResty
        uses: actions/cache@v4
        id: cache-openresty
        with:
          path: |
            ${{ env.OPENRESTY_PREFIX }}
            work/
          key: v2::${{ runner.os }}-openresty-${{ matrix.openresty }}-${{ hashFiles('.resty-opts') }}

      - name: install OpenResty build deps
        if: steps.cache-openresty.outputs.cache-hit != 'true'
        id: openresty-deps
        run: |
          sudo apt-get install -y libpcre3-dev

      - name: setup OpenResty
        if: steps.cache-openresty.outputs.cache-hit != 'true'
        id: setup-openresty
        uses: thibaultcha/setup-openresty@main
        with:
          version: ${{ matrix.openresty }}
          openssl-version: ${{ matrix.openssl }}
          test-nginx: true
          debug: true
          opt: ${{ matrix.openresty-opts }}

      - name: Cleanup OpenResty build artifacts
        if: steps.cache-openresty.outputs.cache-hit != 'true'
        run: |
          rm -rf \
            ./work/OpenResty \
            ./work/OpenSSL/test \
            ./work/OpenSSL/doc \
            ./work/OpenSSL/test \
            ./work/OpenSSL/demos \
            ./work/OpenSSL/fuzz \
            ./work/downloads \
          || true

      - name: add OpenResty bin dirs to PATH
        run: |
          echo ${OPENRESTY_PREFIX}/bin >> $GITHUB_PATH
          echo ${OPENRESTY_PREFIX}/luajit/bin >> $GITHUB_PATH
          echo ${OPENRESTY_PREFIX}/nginx/sbin >> $GITHUB_PATH

      - name: checkout resty-cli repo
        uses: actions/checkout@v4
        with:
          repository: openresty/resty-cli
          ref: ${{ matrix.resty-cli }}
          path: resty-cli

      - name: copy & patch files
        run: ./tests/setup-resty-cli.sh

      - name: sanity (nginx -V <> rusty-cli -V)
        run: |
          split_args() {
            sed -r -e '/^configure arguments:.*/ s/ (--?)/\n\1/g'
          }

          echo "::group::nginx -V"
          nginx -V 2>&1 | split_args
          echo "::endgroup::"

          echo "::group::rusty-cli -V"
          rusty-cli -V 2>&1 | split_args
          echo "::endgroup::"

      - name: sanity (rusty-cli w/ gdb)
        run: |
          rusty-cli \
             --gdb-opts="--nx -batch -ex 'b main' -ex run -ex bt -ex 'b lj_cf_io_method_write' -ex c -ex bt" \
             -e 'io.stderr:write("hello world!~~\n")'

      - name: prove
        run: prove -r t/

      - name: runner opts
        run: ./tests/runners.sh

      - name: nginx.conf generation
        run: ./tests/conf-generation.sh

      - name: lua script argv translation
        run: ./tests/lua-arg.sh

      - name: signal-handling
        run: ./tests/sigwinch.sh

      - name: nginx binary location
        run: ./tests/nginx-bin-search.sh
